//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarudzbeDetalji
    {
        public int Id { get; set; }
        public Nullable<int> NarudzbaId { get; set; }
        public Nullable<int> ProizvodId { get; set; }
        public decimal Kolicina { get; set; }
        public decimal JedCijena { get; set; }
    
        public virtual Narudzbe Narudzbe { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
