//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbe()
        {
            this.NarudzbeDetaljis = new HashSet<NarudzbeDetalji>();
        }
    
        public int Id { get; set; }
        public int KorisnikId { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public System.DateTime DatumVrijemeDostave { get; set; }
        public bool JeDostavljeno { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarudzbeDetalji> NarudzbeDetaljis { get; set; }
    }
}
