//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adresar.KontaktService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kontakt", Namespace="http://schemas.datacontract.org/2004/07/Adresar.WCFService.Models")]
    [System.SerializableAttribute()]
    public partial class Kontakt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktivanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobitelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NapomenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa {
            get {
                return this.AdresaField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresaField, value) != true)) {
                    this.AdresaField = value;
                    this.RaisePropertyChanged("Adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktivan {
            get {
                return this.AktivanField;
            }
            set {
                if ((this.AktivanField.Equals(value) != true)) {
                    this.AktivanField = value;
                    this.RaisePropertyChanged("Aktivan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobitel {
            get {
                return this.MobitelField;
            }
            set {
                if ((object.ReferenceEquals(this.MobitelField, value) != true)) {
                    this.MobitelField = value;
                    this.RaisePropertyChanged("Mobitel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Napomena {
            get {
                return this.NapomenaField;
            }
            set {
                if ((object.ReferenceEquals(this.NapomenaField, value) != true)) {
                    this.NapomenaField = value;
                    this.RaisePropertyChanged("Napomena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KontaktService.IKontaktService")]
    public interface IKontaktService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/DohvatiAktivneKontakte", ReplyAction="http://tempuri.org/IKontaktService/DohvatiAktivneKontakteResponse")]
        Adresar.KontaktService.Kontakt[] DohvatiAktivneKontakte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontaktService/DohvatiAktivneKontakte", ReplyAction="http://tempuri.org/IKontaktService/DohvatiAktivneKontakteResponse")]
        System.Threading.Tasks.Task<Adresar.KontaktService.Kontakt[]> DohvatiAktivneKontakteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKontaktServiceChannel : Adresar.KontaktService.IKontaktService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KontaktServiceClient : System.ServiceModel.ClientBase<Adresar.KontaktService.IKontaktService>, Adresar.KontaktService.IKontaktService {
        
        public KontaktServiceClient() {
        }
        
        public KontaktServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KontaktServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KontaktServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KontaktServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Adresar.KontaktService.Kontakt[] DohvatiAktivneKontakte() {
            return base.Channel.DohvatiAktivneKontakte();
        }
        
        public System.Threading.Tasks.Task<Adresar.KontaktService.Kontakt[]> DohvatiAktivneKontakteAsync() {
            return base.Channel.DohvatiAktivneKontakteAsync();
        }
    }
}
